trivia_questions = {
    "The Great Wall of China is visible from space.": "False",
    "Sharks are mammals.": "False",
    "The Amazon River is the longest river in the world.": "False",
    "Bananas grow on trees.": "False",
    "Venus is the hottest planet in our solar system.": "True",
    "A group of crows is called a murder.": "True",
    "Goldfish have a memory span of three seconds.": "False",
    "The speed of light is faster than the speed of sound.": "True",
    "The capital of Australia is Sydney.": "False",
    "Mount Everest is the tallest mountain on Earth.": "True",
    "Humans share about 60% of their DNA with bananas.": "True",
    "Penguins can fly.": "False",
    "Lightning never strikes the same place twice.": "False",
    "Bats are blind.": "False",
    "Octopuses have three hearts.": "True",
    "The Earth orbits the Sun once every 365 days.": "True",
    "There are 100 minutes in an hour.": "False",
    "Water boils at 100 degrees Celsius at sea level.": "True",
    "The Mona Lisa was painted by Vincent van Gogh.": "False",
    "Dogs sweat through their tongues.": "False",
    "The human body has four lungs.": "False",
    "The Great Pyramid of Giza is one of the Seven Wonders of the Ancient World.": "True",
    "A triangle can have more than one right angle.": "False",
    "Dolphins sleep with one eye open.": "True",
    "The Sahara Desert is the largest desert in the world.": "True",
    "Sound travels faster in air than in water.": "False",
    "An ostrich's eye is bigger than its brain.": "True",
    "The human body is about 60% water.": "True",
    "Camels store water in their humps.": "False",
    "The Moon has its own light.": "False",
    "Jellyfish have no brain.": "True",
    "The Statue of Liberty was a gift from France.": "True",
    "The boiling point of water is the same at all altitudes.": "False",
    "Polar bears can only live in the Arctic.": "True",
    "The Pacific Ocean is the largest ocean on Earth.": "True",
    "Spiders are insects.": "False",
    "Neil Armstrong was the first person to walk on the Moon.": "True",
    "A leap year has 366 days.": "True",
    "Tomatoes are vegetables.": "False",
    "The Eiffel Tower is taller than the Empire State Building.": "False",
    "Peanuts are a type of nut.": "False",
    "Saturn is the only planet with rings.": "False",
    "Albert Einstein was awarded the Nobel Prize for the theory of relativity.": "False",
    "The Milky Way is a type of galaxy.": "True",
    "Humans have 32 permanent teeth.": "True",
    "The Roman numeral for 50 is L.": "True",
    "Fire needs oxygen to burn.": "True",
    "Cats are herbivores.": "False",
    "The blue whale is the largest animal ever known to have lived.": "True",
    "Cacti can survive in cold environments.": "True",
}